version: '3.8'

services:
  db:
    image: postgres:10
    container_name: odoo_postgres
    environment:
      - POSTGRES_DB=escuelafullstack
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "5432:5432"

  odoo:
    image: odoo:13.0
    container_name: odoo_app
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo_web_data:/var/lib/odoo
      - ./filestore:/var/lib/odoo/.local/share/Odoo/filestore/escuelafullstack
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons

volumes:
  odoo_db_data:
  odoo_web_data:
